workspace:
  base: /opt
  path: web/pacman

pipeline:
  - image: plugins/golang
    commands:
      - go get -t -v ./...
      - go test ./...
    envs:
      DEBUG: true
    when:
      event:
        - push
        - pull_request
        - tag

registry:
  - name: pacman
    settings:
      auto_tag: true
      auto_tag_suffix: release
      dockerfile: "./Dockerfile"
      secret:
        password: docker_password
        username: docker_username
    when:
      event:
        - push
        - tag
