workspace:
  base: /opt
  path: web/pacman

pipeline:
  - image: golang
    commands:
      - go get -t -v ./...
      - go test ./...
    envs:
      DEBUG: true
    when:
      event:
        - push
        - pull_request
        - tag
  - plugin: slack
    settings:
      endpoint: "https://api.dummy.com/slack.send"
      token: 
        from_secret: "slack_auth"
    when:
      event:
        - failed

registry:
  - name: pacman
    settings:
      auto_tag: true
      auto_tag_suffix: release
      dockerfile: "./Dockerfile"
      secret:
        password: docker_password
        username: docker_username
    when:
      event:
        - push
        - tag
